mysql:
  ip: 192.168.1.158
  port: 3306
spring:
  datasource:
    name: ${spring.profiles.active}
    url: jdbc:mysql://${mysql.ip}:${mysql.port}/steward?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: dev
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: false
      maxActive: 100
      initialSize: 3
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: 192.168.1.158
    port: 6379
    password: 123456
    timeout: 3000
    database: 1
    jedis:
      pool:
        maxactive: 600
        maxIdle: 300
        minIdle: 10
        maxWait: 1000